### ISSUE TITLE
Install BUG, migrate

### ISSUE THREAD

**Issue by eightsixeight** [mwolff44/pyfreebilling#164]
new install all ok a part from a few jessie/trusty issues..

but python manage.py migrate crashes on a missing column...

  Applying axes.0002_auto_20151217_2044... OK
  Applying axes.0003_auto_20160322_0929... OK
  Applying cdr.0001_initial... OK
  Applying cdr.0002_auto_20161116_1546... OK
  Applying cdr.0003_auto_20161129_0955... OK
  Applying cdr.0004_auto_20170522_1123... OK
  Applying cdr.0005_remove_cdr_customerdirectory_id... OK
  Applying cdr.0006_auto_20171222_1716... OK
  Applying chroniker.0001_initial... OK
  Applying currencies.0002_alter_model... OK
  Applying customerdirectory.0017_auto_20180207_1116... OK
  Applying customerdirectory.0018_auto_20180406_1732...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 108, in database_forwards
    self._run_sql(schema_editor, self.sql)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 133, in _run_sql
    schema_editor.execute(statement, params=None)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: column sg.sip_port does not exist
LINE 1: ....proxy AS VARCHAR) AS ip_addr,  32 AS mask,  CAST(sg.sip_por...
                                                             ^

**Comment by eightsixeight** [comment]
bug on install

**Comment by mwolff44** [comment]
did you resolve it ?

**Comment by eightsixeight** [comment]
yes  reinstalled it all

**Comment by mwolff44** [comment]
OK, i close the issue
