### ISSUE TITLE
Install BUG, migrate

### ISSUE THREAD

**Issue by stilet** [mwolff44/pyfreebilling#180]
new install all ok a part from a few Ubuntu 18.04

docker-compose -f production.yml run --rm django python manage.py migrate

Applying pyfb_normalization.0001_initial... OK
  Applying pyfb_endpoint.0001_initial... OK
  Applying pyfb_endpoint.0002_auto_20181218_1700... OK
  Applying pyfb_endpoint.0003_auto_20181219_1354... OK
  Applying pyfb_endpoint.0004_auto_20181219_1402... OK
  Applying pyfb_endpoint.0005_auto_20190130_1417...Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedTable: relation "pyfb_routing_c_routinggrp" does not exist
LINE 1: ...modified FROM pyfb_endpoint_customer c INNER JOIN pyfb_routi...
                                                             ^
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/special.py", line 105, in database_forwards
    self._run_sql(schema_editor, self.sql)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/special.py", line 130, in _run_sql
    schema_editor.execute(statement, params=None)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "pyfb_routing_c_routinggrp" does not exist
LINE 1: ...modified FROM pyfb_endpoint_customer c INNER JOIN pyfb_routi...

Thanks

**Comment by mwolff44** [comment]
Hi,
Which version do you try to install ?
If you want to test PyFreeBilling v3, you have to use gitlab sources (just change giythub to gitlab.
Regards

**Comment by stilet** [comment]
Hi! I'm using the master branch from this repository.

**Comment by mwolff44** [comment]
Hi,
Please use this one : https://gitlab.com/mwolff44/pyfreebilling.
Due to recent github issues, i only update the gitlab one.
